version: '3'

networks:
    dockercomposefiles_devbadger-network:
     external: true

services:

  wiremock-server:
    image: com.devbadger/wiremock:1.0.0-SNAPSHOT
    ports:
      - 14551:8080
    networks:
      - dockercomposefiles_devbadger-network
    volumes:
      - ./wiremock/mounted/mappings:/app/mappings
      - ./wiremock/mounted/logs:/app/logs

  eureka:
    image: com.devbadger/eureka:1.0.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001
    ports:
      - 11557:8080
      - 12557:8001
    networks:
      - dockercomposefiles_devbadger-network

  config:
    image: com.devbadger/config:1.0.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001
    ports:
      - 11556:8080
      - 12556:8001
    volumes:
      - /Users/$USER/.ssh/id_rsa:/root/.ssh/id_rsa
      - /Users/$USER/.ssh/known_hosts:/root/.ssh/known_hosts
    networks:
      - dockercomposefiles_devbadger-network

  zuul:
    image: com.devbadger/zuul:1.0.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001
    ports:
      - 8443:8080
      - 12550:8001
    networks:
      - dockercomposefiles_devbadger-network

#  security:
#    image: com.devbadger/security:1.0.0-SNAPSHOT
#    environment:
#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=12551
#    ports:
#      - 11553:8080
#      - 12553:8001
#    networks:
#      - dockercomposefiles_devbadger-network
#
  gateway:
    image: com.devbadger/gateway:1.0.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=12552
    ports:
      - 11552:8080
      - 12552:8001
    networks:
      - dockercomposefiles_devbadger-network

  service:
    image: com.devbadger/service:1.0.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=12553
      - VIRTUAL_HOST=*/flex-service/*,https://*/flex-service/*
    ports:
      - 11551:8080
      - 12551:8001
    networks:
      - dockercomposefiles_devbadger-network